name: marcusataide
favicon: null
layout_spectrum: 0.9073950399179012
typography_spectrum: 0.5631494051776826
title: Marcus Ataide
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6795064876787364
  lightness: 0.6191649490501732
  saturation: 0.5675261761061847
  rhythmicContrast: 0.558498157421127
purpose: []
