name: marcusataide
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5631494051776826
title: Marcus Ataide
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000201'
    - '#28917e'
    - '#bdf2f8'
    - '#033b21'
    - '#95c2c6'
  brandStrength: 0.875
  lightness: 0.6191649490501732
  saturation: 0.5675261761061847
  rhythmicContrast: 0.558498157421127
purpose: []
